import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from 'sonner';
import { Analytics } from '@vercel/analytics/react';
import Provider from '@/components/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Chat-PDF',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<Provider>
				<html lang="en">
					<body className={inter.className}>
						{children}
						<Toaster />
						<Analytics />
					</body>
				</html>
			</Provider>
		</ClerkProvider>
	);
}
